### ISSUE TITLE
#011-Section-9(The ideal solution for your business)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Netflix-Ninjas_066#16]
@vivekkmrpaswan 
Design Section-6(Coursera+)

**Steps to Reproduce**:

- [x] Add Table design
- [x] Use sponsor logos. 
- [x] Add Responsiveness.
- [ ] Add button and use json to make it more dynamic.

**Possible Solution**:
Use Bootstrap framework..

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3
Related issue: #11

**Comment by vivekkmrpaswan** [comment]
Overview:
This request addresses an issue where Sections 9, 10, and 11 were misaligned on smaller screens, causing a poor user experience. The fix ensures that Sections 9, 10, and 11 align correctly across all devices.
Changes:

- [ ] Responsiveness Added

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #16

![Screenshot 2024-06-12 112048](https://github.com/Mayank1st/Netflix-Ninjas_066/assets/167101531/8875eca8-069c-4fa2-8023-f9b8fdc99761)
![Screenshot 2024-06-13 005817](https://github.com/Mayank1st/Netflix-Ninjas_066/assets/167101531/9942525d-4aa5-4025-a486-f2b5ec05c74c)
![Screenshot 2024-06-14 004643](https://github.com/Mayank1st/Netflix-Ninjas_066/assets/167101531/9127106d-cc1c-4ae1-b1a9-9c99c0354ea0)
