### ISSUE TITLE
#013-section-11(Footer)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Netflix-Ninjas_066#9]
@vivekkmrpaswan 
Design **Footer**

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate anchor tag
- [x] Add Responsiveness.

**Possible Solution**:
Use Bootstrap framework..

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3
Related issue: #13

**Comment by vivekkmrpaswan** [comment]
- [ ] Open the website on Chrome browser.

![Screenshot 2024-06-14 004643](https://github.com/Mayank1st/Netflix-Ninjas_066/assets/167101531/220046c3-ff4c-4987-8260-dd8386680712)

**Comment by vivekkmrpaswan** [comment]
Overview:
This request addresses an issue where Section 11 was misaligned on smaller screens, causing a poor user experience. The fix ensures that Section 11 aligns correctly across all devices.
Changes:

- [ ] Responsiveness Added

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #13

![Screenshot 2024-06-12 112048](https://github.com/Mayank1st/Netflix-Ninjas_066/assets/167101531/387b8a0e-00ff-4b43-a9b3-864749189681)
